version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db
    networks:
      springboot-mysql-net:

  springboot-restful-services:
    container_name: springboot-restful-services
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "1000:8080"
    depends_on:
      - mysqldb
    networks:
        springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net: